window.I18N = {
    'zh-CN': {
        extName: 'PlainTab · 极简起始页',
        searchPlaceholder: '在 Web 中搜索…',
        engineTitle: '点击切换搜索引擎 | 回车搜索',
        langTitle: '切换语言',
        settingsTitle: '壁纸设置',
        panelTitle: '壁纸',
        wpBing: 'Bing 每日壁纸',
        wpLocal: '本地壁纸',
        uploadBtn: '选择本地壁纸',
        resetBtn: '恢复 Bing 每日壁纸',
        advToggle: '高级选项',
        searchLabel: '搜索栏显示',
        searchHover: '悬停时显示',
        searchAlways: '始终显示',
        searchNever: '始终隐藏',
        searchHistory: '搜索历史',
        searchHistoryOff: '关闭',
        opacityLabel: '图标不透明度',
        panelOpacityLabel: '面板透明度',
        themeEnableLabel: '启用壁纸主题色',
        engineLabel: '搜索引擎',
        resetAdv: '恢复默认设置',
        langPanelTitle: '语言',
        addImage: '添加壁纸',
        deleteImage: '删除',
        imageCount: '张',
        resetConfirm: '确定删除所有本地壁纸？此操作不可撤销。',
        searchPosition: '搜索栏位置',
        posEdgeTop: '贴近顶部',
        posTop: '顶部',
        posHigh: '居上',
        posUpper: '中上',
        posCenterUpper: '居中偏上',
        posCenter: '居中',
        posCenterLower: '居中偏下',
        posLower: '中下',
        posBottom: '底部',
        posLow: '居下',
        posEdgeBottom: '贴近底部',
        posTopLeft: '左上',
        posTopCenter: '上方居中',
        posTopRight: '右上',
        posCenterLeft: '左侧居中',
        posCenterRight: '右侧居中',
        posBottomLeft: '左下',
        posBottomCenter: '下方居中',
        posBottomRight: '右下',
        searchAlign: '搜索栏横向',
        alignLeft: '靠左',
        alignCenter: '居中',
        alignRight: '靠右',
        searchIconPosition: '搜索图标位置',
        iconLeft: '左侧',
        iconRight: '右侧',
        searchWidth: '搜索栏宽度',
        searchRadius: '搜索栏圆角',
        radiusCapsule: '胶囊 (偏圆)',
        radiusRounded: '圆角',
        radiusSharp: '直角',
        searchBackground: '搜索框背景',
        searchBlur: '搜索框模糊',
        wallpaperFit: '壁纸适配',
        fitCover: '铺满裁切',
        fitContain: '完整显示',
        fitStretch: '拉伸填充',
        wallpaperPosition: '壁纸焦点',
        wallpaperBlur: '背景模糊',
        wallpaperApply: '应用配置',
        wallpaperApplyReady: '可以应用配置',
        wallpaperApplyNoChanges: '没有未应用更改',
        wallpaperDiscardCacheConfirm: '切换来源会丢弃当前来源已缓存的壁纸数据。继续吗？',
        rssNeedsSource: '请添加并选择 RSS 源',
        apiNeedsSource: '请添加并选择 API 源',
        rssNeedsTest: '当前 RSS 源需要测试通过',
        apiNeedsTest: '当前 API 源需要测试通过',
        apiNeedsFreshTest: '请重新测试当前 API 源',
        folderNeedsValidSelection: '请选择有效文件夹',
        settingsGroupTheme: '主题',
        settingsGroupSearch: '搜索栏',
        settingsGroupSearchVisibility: '显示',
        settingsGroupSearchLayout: '布局',
        settingsGroupSearchSurface: '样式',
        settingsGroupSearchEngine: '搜索引擎',
        settingsGroupWallpaper: '壁纸',
        settingsGroupSurface: '界面',
        cpGroupAppearance: '外观',
        cpGroupOpen: '打开方式',
        cpGroupContent: '内容',
        cpSkinLabel: '命令面板样式',
        cpSkinDefault: '常规',
        cpSkinTerminal: '极客',
        cpSkinShell: '控制台',
        cpSkinCommandTerminal: '终端 · 推荐',
        uiRadiusLabel: '界面圆角',
        radiusCompact: '克制',
        radiusSoft: '柔和',
        radiusRound: '圆润',
        overlayLabel: '壁纸遮罩',
        cpHotkeyLabel: '命令面板快捷键',
        cpHiddenHotkeyLabel: '隐藏面板快捷键',
        cpRecommendLabel: '显示推荐',
        cpSearchPlaceholder: '搜索快捷链接…',
        tabAppearance: '界面',
        tabSearch: '搜索',
        tabWallpaper: '壁纸',
        tabShortcuts: '命令面板',
        tabPermissions: '权限',
        tabData: '数据',
        tabAbout: '关于',
        pressCombo: '按下组合键...',
        needCtrl: '需要 Ctrl 键',
        needLetter: '需要字母键 A-Z',
        hotkeyConflict: '快捷键冲突',
        sourceBing: 'Bing 每日壁纸',
        sourceBingDesc: '每日自动更新，根据语言选择地区',
        sourceUpload: '本地上传',
        sourceUploadDesc: '上传图片，最多 12 张轮换',
        sourceFolder: '本地文件夹',
        sourceFolderDesc: '从本地文件夹直接读取图片',
        sourceRss: 'RSS 订阅',
        sourceRssDesc: '从 RSS Feed 自动下载图片',
        sourceApi: 'API 端点',
        sourceApiDesc: '从 API 接口获取图片 URL',
        bingConfigHint: '根据当前界面语言自动选择 Bing 市场区域。',
        uploadConfigHint: '在一级面板中使用「+」按钮上传图片。',
        noFolderSelected: '未选择文件夹',
        chooseFolder: '选择文件夹',
        strategyRandom: '随机',
        strategySequential: '顺序',
        folderUnsupported: '当前浏览器不支持文件夹壁纸',
        folderReady: '已准备文件夹：',
        folderSaved: '已保存文件夹：',
        folderImagesUnit: '张图片',
        folderNeedsPermission: '需要重新授权文件夹',
        folderEmpty: '未找到支持的图片',
        folderNoUsableImages: '找到图片，但无法读取可用壁纸',
        folderPreviewFailed: '无法生成文件夹壁纸预览',
        folderPreparing: '正在读取...',
        folderRotation: '轮换方式',
        rssConfigHint: '支持 RSS 2.0 / Atom，自动提取 enclosure、media:content 中的图片',
        fetchImages: '拉取图片',
        saveConfig: '保存配置',
        jsonPathPlaceholder: 'JSON 图片路径，如 data.image.url',
        sourcePendingHint: '这个来源的配置正在接入中，当前还不会改变壁纸。',
        folderPendingHint: '文件夹读取需要先完成目录授权和轮换策略。',
        rssPendingHint: 'RSS 订阅需要先完成抓取、解析和缓存流程。',
        apiPendingHint: 'API 端点需要先完成 URL 校验和 JSON 路径解析。',
        apiTest: '测试',
        apiTypeImage: '图片直链/重定向',
        apiTypeJson: 'JSON',
        apiRefreshEveryTab: '每次打开',
        apiLimit: '最多 5 个 API 源',
        apiInvalidUrl: '请输入 https:// 链接',
        apiAuthRequired: '该接口可能需要鉴权，当前版本仅支持把 token 放在 URL 参数里的 GET 接口',
        apiCorsFailed: '请求失败，可能是 CORS、网络或权限限制',
        apiTimeout: 'API 请求超时',
        apiJsonParseFailed: 'JSON 内容无法解析',
        apiJsonPathFailed: '没有从 JSON 中找到图片 URL',
        apiNotImage: '响应不是图片',
        apiImageDownloadFailed: '图片下载失败',
        apiTestOk: '测试通过',
        dataExport: '导出',
        dataImport: '导入',
        dataExportJson: '导出 JSON',
        dataExportEncrypted: '导出加密文件',
        dataEncrypted: '加密',
        dataBackupFile: '备份文件',
        dataImportPass: '导入口令',
        dataPassphrase: '口令',
        dataChooseFile: '选择文件',
        dataExporting: '正在导出...',
        dataImporting: '正在导入...',
        dataExportOk: '导出完成',
        dataImportOk: '导入完成',
        dataExportFailed: '导出失败：',
        dataImportFailed: '导入失败：',
        dataPassRequired: '请输入加密口令',
        dataCryptoUnsupported: '当前浏览器不支持加密备份',
        dataInvalidBackup: '备份文件无效',
        modalDescPaletteSkin: '常规跟随主题色；其他样式使用独立配色。推荐使用终端样式，支持右下角临时调整大小。',
        permissionGroupWebAccess: '网页读取',
        webAccessTitle: 'HTTPS 网站读取权限',
        webAccessGrant: '一次性授权 HTTPS 网站',
        webAccessRevoke: '改回按需授权',
        permissionUsesLabel: '用途',
        permissionUseShortcut: '快捷方式标题',
        permissionUseRss: 'RSS 测试',
        permissionUseApi: 'API 读取',
        webAccessHint: '默认会按站点请求授权；一次性授权后，PlainTab 可在 HTTPS 站点上更顺畅地自动读取标题与测试数据源。',
        webAccessChecking: '正在检查权限...',
        webAccessEnabled: '已授权所有 HTTPS 网站读取',
        webAccessDisabled: '按需授权；未授权时使用降级名称',
        webAccessUnsupported: '仅扩展模式支持此授权',
        webAccessRequesting: '等待浏览器授权确认...',
        webAccessGrantOk: '已启用 HTTPS 网站读取权限',
        webAccessGrantCanceled: '授权已取消',
        webAccessRevokeOk: '已改回按需获取',
        webAccessRevokeFailed: '没有可撤销的 HTTPS 网站读取授权',
        modalSubtitlePermissions: '快捷方式、RSS 和 API 共用的浏览器权限放在这里。',
        modalDescWebAccess: '用于添加快捷方式时获取网页标题，也用于 RSS/API 测试与读取你配置的数据源。PlainTab 不会修改网页内容。',
        modalSubtitleData: '导出或恢复 PlainTab 的完整用户配置。',
        modalDescSearchHistory: '在搜索栏下方保留最近搜索。',
        modalDescDataJson: 'JSON 方便留存和排查。',
        modalDescDataEncrypted: '加密文件会先压缩再加密，体积通常更小。',
        modalDescDataImport: '支持 JSON 或加密备份文件。',
        modalDescDataImportPass: '仅导入加密文件时需要。',
        aboutDesc: '一款零闪白、极简纯粹的浏览器新标签页扩展。支持五种壁纸来源，双层渲染引擎确保首帧即壁纸。',
        aboutFooter: 'Made by kaininx · MIT License',
    },
    'zh-TW': {
        extName: 'PlainTab · 極簡起始頁',
        searchPlaceholder: '在 Web 中搜尋…',
        engineTitle: '點擊切換搜尋引擎 | Enter 搜尋',
        langTitle: '切換語言',
        settingsTitle: '桌布設定',
        panelTitle: '桌布',
        wpBing: 'Bing 每日桌布',
        wpLocal: '本機圖片',
        uploadBtn: '選擇本機桌布',
        resetBtn: '回復為 Bing 每日桌布',
        advToggle: '進階選項',
        searchLabel: '搜尋列顯示',
        searchHover: '懸停時顯示',
        searchAlways: '始終顯示',
        searchNever: '始終隱藏',
        opacityLabel: '圖示不透明度',
        panelOpacityLabel: '面板透明度',
        themeEnableLabel: '启用壁纸主题色',
        engineLabel: '搜尋引擎',
        resetAdv: '回復預設值',
        langPanelTitle: '語言',
        addImage: '新增桌布',
        deleteImage: '刪除',
        imageCount: '張',
        resetConfirm: '確定刪除所有本機桌布？此操作無法復原。'
    },
    'en': {
        extName: 'PlainTab · Minimal New Tab',
        searchPlaceholder: 'Search the Web…',
        engineTitle: 'Click to switch engine | Enter to search',
        langTitle: 'Switch Language',
        settingsTitle: 'Wallpaper Settings',
        panelTitle: 'Wallpaper',
        wpBing: 'Bing Daily',
        wpLocal: 'Local Wallpaper',
        uploadBtn: 'Choose Local Wallpaper',
        resetBtn: 'Restore Bing Daily',
        advToggle: 'Advanced Options',
        searchLabel: 'Search Bar Visibility',
        searchHover: 'Show on Hover',
        searchAlways: 'Always Visible',
        searchNever: 'Always Hidden',
        searchHistory: 'Search History',
        searchHistoryOff: 'Off',
        opacityLabel: 'Icon Opacity',
        panelOpacityLabel: 'Panel Opacity',
        themeEnableLabel: 'Enable Wallpaper Theme',
        engineLabel: 'Search Engine',
        resetAdv: 'Restore Defaults',
        langPanelTitle: 'Language',
        addImage: 'Add Wallpaper',
        deleteImage: 'Remove',
        imageCount: 'images',
        resetConfirm: 'Remove all local wallpapers? This cannot be undone.',
        searchPosition: 'Search Bar Position',
        posEdgeTop: 'Near Top',
        posTop: 'Top',
        posHigh: 'High',
        posUpper: 'Upper',
        posCenterUpper: 'Above Center',
        posCenter: 'Center',
        posCenterLower: 'Below Center',
        posLower: 'Lower',
        posBottom: 'Bottom',
        posLow: 'Low',
        posEdgeBottom: 'Near Bottom',
        posTopLeft: 'Top Left',
        posTopCenter: 'Top Center',
        posTopRight: 'Top Right',
        posCenterLeft: 'Center Left',
        posCenterRight: 'Center Right',
        posBottomLeft: 'Bottom Left',
        posBottomCenter: 'Bottom Center',
        posBottomRight: 'Bottom Right',
        searchAlign: 'Search Bar Alignment',
        alignLeft: 'Left',
        alignCenter: 'Center',
        alignRight: 'Right',
        searchIconPosition: 'Search Icon Position',
        iconLeft: 'Left',
        iconRight: 'Right',
        searchWidth: 'Search Bar Width',
        searchRadius: 'Search Bar Radius',
        radiusCapsule: 'Capsule (Round)',
        radiusRounded: 'Rounded',
        radiusSharp: 'Sharp',
        searchBackground: 'Search Background',
        searchBlur: 'Search Glass Blur',
        wallpaperFit: 'Wallpaper Fit',
        fitCover: 'Cover and Crop',
        fitContain: 'Show Full Image',
        fitStretch: 'Stretch to Fill',
        wallpaperPosition: 'Wallpaper Focus',
        wallpaperBlur: 'Background Blur',
        wallpaperApply: 'Apply configuration',
        wallpaperApplyReady: 'Ready to apply',
        wallpaperApplyNoChanges: 'No unapplied changes',
        wallpaperDiscardCacheConfirm: 'Switching source will discard cached wallpaper data for the current source. Continue?',
        rssNeedsSource: 'Add and select an RSS source',
        apiNeedsSource: 'Add and select an API source',
        rssNeedsTest: 'Test the current RSS source first',
        apiNeedsTest: 'Test the current API source first',
        apiNeedsFreshTest: 'Retest the current API source',
        folderNeedsValidSelection: 'Select a valid folder first',
        settingsGroupTheme: 'Theme',
        settingsGroupSearch: 'Search',
        settingsGroupSearchVisibility: 'Visibility',
        settingsGroupSearchLayout: 'Layout',
        settingsGroupSearchSurface: 'Surface',
        settingsGroupSearchEngine: 'Search Engine',
        settingsGroupWallpaper: 'Wallpaper',
        settingsGroupSurface: 'Interface',
        cpGroupAppearance: 'Appearance',
        cpGroupOpen: 'Open',
        cpGroupContent: 'Content',
        cpSkinLabel: 'Command Panel Style',
        cpSkinDefault: 'Regular',
        cpSkinTerminal: 'Geek',
        cpSkinShell: 'Console',
        cpSkinCommandTerminal: 'Terminal · Recommended',
        uiRadiusLabel: 'Interface Radius',
        radiusCompact: 'Compact',
        radiusSoft: 'Soft',
        radiusRound: 'Round',
        overlayLabel: 'Wallpaper Mask',
        cpHotkeyLabel: 'Command Palette Hotkey',
        cpHiddenHotkeyLabel: 'Hidden Palette Hotkey',
        cpRecommendLabel: 'Show Recommendations',
        cpSearchPlaceholder: 'Search shortcuts...',
        tabAppearance: 'Appearance',
        tabSearch: 'Search',
        tabWallpaper: 'Wallpaper',
        tabShortcuts: 'Command Panel',
        tabPermissions: 'Permissions',
        tabData: 'Data',
        tabAbout: 'About',
        pressCombo: 'Press key combo...',
        needCtrl: 'Ctrl key required',
        needLetter: 'Letter A-Z required',
        hotkeyConflict: 'Conflict!',
        sourceBing: 'Bing Daily Wallpaper',
        sourceBingDesc: 'Auto-updates daily, region based on language',
        sourceUpload: 'Local Upload',
        sourceUploadDesc: 'Upload images, up to 12 rotating',
        sourceFolder: 'Local Folder',
        sourceFolderDesc: 'Read images directly from disk',
        sourceRss: 'RSS Feed',
        sourceRssDesc: 'Auto-download images from RSS feed',
        sourceApi: 'API Endpoint',
        sourceApiDesc: 'Fetch image URL from API endpoint',
        bingConfigHint: 'Bing market region is automatically selected based on your language.',
        uploadConfigHint: 'Use the + button in the quick panel to upload. Supports multi-select, up to 12.',
        noFolderSelected: 'No folder selected',
        chooseFolder: 'Choose Folder',
        strategyRandom: 'Random',
        strategySequential: 'Sequential',
        folderUnsupported: 'This browser does not support folder wallpaper',
        folderReady: 'Folder ready: ',
        folderSaved: 'Saved folder: ',
        folderImagesUnit: 'images',
        folderNeedsPermission: 'Folder permission needs to be granted again',
        folderEmpty: 'No supported images found',
        folderNoUsableImages: 'Images were found, but none could be read',
        folderPreviewFailed: 'Could not prepare the folder wallpaper preview',
        folderPreparing: 'Reading...',
        folderRotation: 'Rotation',
        rssConfigHint: 'Supports RSS 2.0 / Atom. Extracts images from enclosure and media:content.',
        fetchImages: 'Fetch Images',
        saveConfig: 'Save Config',
        jsonPathPlaceholder: 'JSON path, e.g. data.image.url',
        sourcePendingHint: 'This source configuration is still being connected and will not change the wallpaper yet.',
        folderPendingHint: 'Folder reading still needs directory permission and rotation strategy support.',
        rssPendingHint: 'RSS still needs fetch, parse, and cache support.',
        apiPendingHint: 'API endpoints still need URL validation and JSON path parsing.',
        apiTest: 'Test',
        apiTypeImage: 'Image/Redirect',
        apiTypeJson: 'JSON',
        apiRefreshEveryTab: 'Every new tab',
        apiLimit: 'Up to 5 API sources',
        apiInvalidUrl: 'Enter an https:// link',
        apiAuthRequired: 'This API may require authentication. This version only supports GET endpoints with tokens in the URL.',
        apiCorsFailed: 'Request failed. CORS, network, or permission limits may be blocking it.',
        apiTimeout: 'API request timed out',
        apiJsonParseFailed: 'JSON content could not be parsed',
        apiJsonPathFailed: 'No image URL was found in the JSON',
        apiNotImage: 'The response is not an image',
        apiImageDownloadFailed: 'Image download failed',
        apiTestOk: 'Test passed',
        dataExport: 'Export',
        dataImport: 'Import',
        dataExportJson: 'Export JSON',
        dataExportEncrypted: 'Export encrypted file',
        dataEncrypted: 'Encrypted',
        dataBackupFile: 'Backup file',
        dataImportPass: 'Import passphrase',
        dataPassphrase: 'Passphrase',
        dataChooseFile: 'Choose file',
        dataExporting: 'Exporting...',
        dataImporting: 'Importing...',
        dataExportOk: 'Export complete',
        dataImportOk: 'Import complete',
        dataExportFailed: 'Export failed: ',
        dataImportFailed: 'Import failed: ',
        dataPassRequired: 'Enter a passphrase',
        dataCryptoUnsupported: 'This browser does not support encrypted backups',
        dataInvalidBackup: 'Invalid backup file',
        modalDescPaletteSkin: 'Regular follows theme colors; the other styles use independent colors. Terminal is recommended and supports temporary resize.',
        permissionGroupWebAccess: 'Web Access',
        webAccessTitle: 'HTTPS site read permission',
        webAccessGrant: 'Allow all HTTPS sites',
        webAccessRevoke: 'Return to on-demand access',
        permissionUsesLabel: 'Uses',
        permissionUseShortcut: 'Shortcut titles',
        permissionUseRss: 'RSS tests',
        permissionUseApi: 'API reads',
        webAccessHint: 'By default PlainTab asks per site. Allowing all HTTPS sites makes title fetching and data-source tests smoother.',
        webAccessChecking: 'Checking permission...',
        webAccessEnabled: 'All HTTPS site reading is allowed',
        webAccessDisabled: 'On-demand access; fallback names are used when not allowed',
        webAccessUnsupported: 'This permission is only available in extension mode',
        webAccessRequesting: 'Waiting for browser permission...',
        webAccessGrantOk: 'HTTPS site reading is enabled',
        webAccessGrantCanceled: 'Permission request canceled',
        webAccessRevokeOk: 'Returned to on-demand access',
        webAccessRevokeFailed: 'No HTTPS site read permission to revoke',
        modalSubtitlePermissions: 'Browser permissions shared by shortcuts, RSS, and API sources live here.',
        modalDescWebAccess: 'Used to read page titles when adding shortcuts, and to test or read RSS/API sources you configure. PlainTab does not modify page content.',
        modalSubtitleData: 'Export or restore the full PlainTab configuration.',
        modalDescSearchHistory: 'Keep recent searches available below the search bar.',
        modalDescDataJson: 'Readable JSON is convenient for archives and troubleshooting.',
        modalDescDataEncrypted: 'Password-protected backup, compressed before encryption.',
        modalDescDataImport: 'Import JSON or encrypted PlainTab backup files.',
        modalDescDataImportPass: 'Required only for encrypted backup files.',
        aboutDesc: 'A zero-flash, minimalist browser new tab extension. Five wallpaper sources, dual-layer rendering engine.',
        aboutFooter: 'Made by kaininx · MIT License'
    },
    'es': {
        extName: 'PlainTab · Página Minimalista',
        searchPlaceholder: 'Buscar en la Web…',
        engineTitle: 'Clic para cambiar motor | Enter para buscar',
        langTitle: 'Cambiar idioma',
        settingsTitle: 'Configuración del fondo',
        panelTitle: 'Fondo de pantalla',
        wpBing: 'Bing diario',
        wpLocal: 'Imagen local',
        uploadBtn: 'Elegir fondo local',
        resetBtn: 'Restablecer a Bing diario',
        advToggle: 'Avanzado',
        searchLabel: 'Visibilidad de búsqueda',
        searchHover: 'Al pasar el cursor',
        searchAlways: 'Siempre visible',
        searchNever: 'Siempre oculta',
        opacityLabel: 'Opacidad del icono',
        panelOpacityLabel: 'Opacidad del panel',
        engineLabel: 'Motor de búsqueda',
        resetAdv: 'Restablecer valores',
        langPanelTitle: 'Idioma',
        addImage: 'Añadir fondo',
        deleteImage: 'Eliminar',
        imageCount: 'imágenes',
        resetConfirm: '¿Eliminar todos los fondos locales? No se puede deshacer.'
    },
    'hi': {
        extName: 'PlainTab · न्यूनतम प्रारंभ पृष्ठ',
        searchPlaceholder: 'वेब पर खोजें…',
        engineTitle: 'इंजन बदलने के लिए क्लिक करें | खोजने के लिए Enter',
        langTitle: 'भाषा बदलें',
        settingsTitle: 'वॉलपेपर सेटिंग',
        panelTitle: 'वॉलपेपर',
        wpBing: 'Bing दैनिक',
        wpLocal: 'स्थानीय चित्र',
        uploadBtn: 'स्थानीय वॉलपेपर चुनें',
        resetBtn: 'Bing दैनिक पर रीसेट करें',
        advToggle: 'उन्नत',
        searchLabel: 'सर्च बार दृश्यता',
        searchHover: 'होवर पर दिखाएं',
        searchAlways: 'हमेशा दृश्य',
        searchNever: 'हमेशा छुपा',
        opacityLabel: 'आइकन अपारदर्शिता',
        panelOpacityLabel: 'पैनल अपारदर्शिता',
        engineLabel: 'खोज इंजन',
        resetAdv: 'डिफ़ॉल्ट बहाल करें',
        langPanelTitle: 'भाषा',
        addImage: 'वॉलपेपर जोड़ें',
        deleteImage: 'हटाएँ',
        imageCount: 'छवियाँ',
        resetConfirm: 'सभी स्थानीय वॉलपेपर हटाएँ? पूर्ववत नहीं किया जा सकता।'
    },
    'ar': {
        extName: 'PlainTab · صفحة بداية بسيطة',
        searchPlaceholder: 'ابحث في الويب…',
        engineTitle: 'انقر لتبديل المحرك | Enter للبحث',
        langTitle: 'تغيير اللغة',
        settingsTitle: 'إعدادات الخلفية',
        panelTitle: 'الخلفية',
        wpBing: 'Bing اليومي',
        wpLocal: 'صورة محلية',
        uploadBtn: 'اختر خلفية محلية',
        resetBtn: 'إعادة تعيين إلى Bing اليومي',
        advToggle: 'متقدم',
        searchLabel: 'ظهور شريط البحث',
        searchHover: 'عند التمرير',
        searchAlways: 'ظاهر دائمًا',
        searchNever: 'مخفي دائمًا',
        opacityLabel: 'شفافية الأيقونة',
        panelOpacityLabel: 'شفافية اللوحة',
        engineLabel: 'محرك البحث',
        resetAdv: 'استعادة الافتراضي',
        langPanelTitle: 'اللغة',
        addImage: 'إضافة خلفية',
        deleteImage: 'حذف',
        imageCount: 'صورة',
        resetConfirm: 'إزالة جميع الخلفيات المحلية؟ لا يمكن التراجع.'
    },
    'pt': {
        extName: 'PlainTab · Página Inicial Minimalista',
        searchPlaceholder: 'Pesquisar na Web…',
        engineTitle: 'Clique para trocar | Enter para buscar',
        langTitle: 'Alterar idioma',
        settingsTitle: 'Configurações do papel de parede',
        panelTitle: 'Papel de parede',
        wpBing: 'Bing diário',
        wpLocal: 'Imagem local',
        uploadBtn: 'Escolher papel de parede local',
        resetBtn: 'Redefinir para Bing diário',
        advToggle: 'Avançado',
        searchLabel: 'Visibilidade da busca',
        searchHover: 'Mostrar ao passar',
        searchAlways: 'Sempre visível',
        searchNever: 'Sempre oculto',
        opacityLabel: 'Opacidade do ícone',
        panelOpacityLabel: 'Opacidade do painel',
        engineLabel: 'Mecanismo de pesquisa',
        resetAdv: 'Restaurar padrões',
        langPanelTitle: 'Idioma',
        addImage: 'Adicionar papel de parede',
        deleteImage: 'Remover',
        imageCount: 'imagens',
        resetConfirm: 'Remover todos os papéis de parede locais? Irreversível.'
    },
    'ru': {
        extName: 'PlainTab · Минималистичная стартовая страница',
        searchPlaceholder: 'Поиск в Интернете…',
        engineTitle: 'Нажмите для смены поисковика | Enter для поиска',
        langTitle: 'Сменить язык',
        settingsTitle: 'Настройки обоев',
        panelTitle: 'Обои',
        wpBing: 'Bing дня',
        wpLocal: 'Локальное изображение',
        uploadBtn: 'Выбрать локальные обои',
        resetBtn: 'Сбросить на Bing дня',
        advToggle: 'Дополнительно',
        searchLabel: 'Видимость поиска',
        searchHover: 'При наведении',
        searchAlways: 'Всегда видна',
        searchNever: 'Всегда скрыта',
        opacityLabel: 'Прозрачность значка',
        engineLabel: 'Поисковая система',
        resetAdv: 'Сбросить настройки',
        langPanelTitle: 'Язык',
        addImage: 'Добавить обои',
        deleteImage: 'Удалить',
        imageCount: 'изобр.',
        resetConfirm: 'Удалить все локальные обои? Отменить нельзя.'
    },
    'ja': {
        extName: 'PlainTab · ミニマルなスタートページ',
        searchPlaceholder: 'Web を検索…',
        engineTitle: '検索エンジン切替 | Enter で検索',
        langTitle: '言語切替',
        settingsTitle: '壁紙設定',
        panelTitle: '壁紙',
        wpBing: 'Bing 毎日壁紙',
        wpLocal: 'ローカル壁紙',
        uploadBtn: 'ローカル壁紙を選択',
        resetBtn: 'Bing 毎日壁紙に戻す',
        advToggle: '詳細設定',
        searchLabel: '検索バー表示',
        searchHover: 'ホバー時に表示',
        searchAlways: '常に表示',
        searchNever: '常に非表示',
        opacityLabel: 'アイコン不透明度',
        engineLabel: '検索エンジン',
        resetAdv: '初期設定に戻す',
        langPanelTitle: '言語',
        addImage: '壁紙を追加',
        deleteImage: '削除',
        imageCount: '枚',
        resetConfirm: 'すべてのローカル壁紙を削除しますか？元に戻せません。'
    },
    'de': {
        extName: 'PlainTab · Minimalistische Startseite',
        searchPlaceholder: 'Im Web suchen…',
        engineTitle: 'Klick zum Wechseln | Enter zum Suchen',
        langTitle: 'Sprache wechseln',
        settingsTitle: 'Hintergrundeinstellungen',
        panelTitle: 'Hintergrund',
        wpBing: 'Bing Tägliches Bild',
        wpLocal: 'Lokales Bild',
        uploadBtn: 'Lokales Hintergrundbild wählen',
        resetBtn: 'Auf Bing Tägliches Bild zurücksetzen',
        advToggle: 'Erweitert',
        searchLabel: 'Suchleiste anzeigen',
        searchHover: 'Beim Überfahren',
        searchAlways: 'Immer sichtbar',
        searchNever: 'Immer versteckt',
        opacityLabel: 'Symbol-Transparenz',
        engineLabel: 'Suchmaschine',
        resetAdv: 'Standard wiederherstellen',
        langPanelTitle: 'Sprache',
        addImage: 'Hintergrund hinzufügen',
        deleteImage: 'Entfernen',
        imageCount: 'Bilder',
        resetConfirm: 'Alle lokalen Hintergründe entfernen? Kann nicht rückgängig gemacht werden.'
    },
    'ko': {
        extName: 'PlainTab · 미니멀 스타트 페이지',
        searchPlaceholder: '웹 검색…',
        engineTitle: '검색 엔진 전환 | Enter로 검색',
        langTitle: '언어 전환',
        settingsTitle: '배경화면 설정',
        panelTitle: '배경화면',
        wpBing: 'Bing 매일 배경',
        wpLocal: '로컬 이미지',
        uploadBtn: '로컬 배경 선택',
        resetBtn: 'Bing 매일 배경으로 복원',
        advToggle: '고급 설정',
        searchLabel: '검색창 표시',
        searchHover: '호버 시 표시',
        searchAlways: '항상 표시',
        searchNever: '항상 숨김',
        opacityLabel: '아이콘 불투명도',
        panelOpacityLabel: '패널 불투명도',
        engineLabel: '검색 엔진',
        resetAdv: '기본값 복원',
        langPanelTitle: '언어',
        addImage: '배경화면 추가',
        deleteImage: '삭제',
        imageCount: '장',
        resetConfirm: '모든 로컬 배경화면을 삭제하시겠습니까? 되돌릴 수 없습니다.'
    },
    'fr': {
        extName: 'PlainTab · Page de démarrage minimaliste',
        searchPlaceholder: 'Rechercher sur le Web…',
        engineTitle: 'Cliquez pour changer | Entrée pour rechercher',
        langTitle: 'Changer de langue',
        settingsTitle: 'Paramètres du fond d\'écran',
        panelTitle: 'Fond d\'écran',
        wpBing: 'Bing du jour',
        wpLocal: 'Image locale',
        uploadBtn: 'Choisir un fond d\'écran local',
        resetBtn: 'Réinitialiser à Bing du jour',
        advToggle: 'Avancé',
        searchLabel: 'Visibilité de la recherche',
        searchHover: 'Au survol',
        searchAlways: 'Toujours visible',
        searchNever: 'Toujours masquée',
        opacityLabel: 'Opacité de l\'icône',
        engineLabel: 'Moteur de recherche',
        resetAdv: 'Restaurer les valeurs',
        langPanelTitle: 'Langue',
        addImage: 'Ajouter un fond d\'écran',
        deleteImage: 'Supprimer',
        imageCount: 'images',
        resetConfirm: 'Supprimer tous les fonds d\'écran locaux ? Irréversible.'
    },
    'it': {
        extName: 'PlainTab · Pagina iniziale minimalista',
        searchPlaceholder: 'Cerca nel Web…',
        engineTitle: 'Clicca per cambiare | Invio per cercare',
        langTitle: 'Cambia lingua',
        settingsTitle: 'Impostazioni sfondo',
        panelTitle: 'Sfondo',
        wpBing: 'Bing giornaliero',
        wpLocal: 'Immagine locale',
        uploadBtn: 'Scegli sfondo locale',
        resetBtn: 'Ripristina a Bing giornaliero',
        advToggle: 'Avanzate',
        searchLabel: 'Visibilità barra di ricerca',
        searchHover: 'Al passaggio del mouse',
        searchAlways: 'Sempre visibile',
        searchNever: 'Sempre nascosta',
        opacityLabel: 'Opacità icona',
        engineLabel: 'Motore di ricerca',
        resetAdv: 'Ripristina predefiniti',
        langPanelTitle: 'Lingua',
        addImage: 'Aggiungi sfondo',
        deleteImage: 'Rimuovi',
        imageCount: 'immagini',
        resetConfirm: 'Rimuovere tutti gli sfondi locali? Non reversibile.'
    },
    'tr': {
        extName: 'PlainTab · Minimal Başlangıç Sayfası',
        searchPlaceholder: 'Web\'de ara…',
        engineTitle: 'Motoru değiştirmek için tıkla | Aramak için Enter',
        langTitle: 'Dil değiştir',
        settingsTitle: 'Duvar kağıdı ayarları',
        panelTitle: 'Duvar Kağıdı',
        wpBing: 'Bing günlük',
        wpLocal: 'Yerel resim',
        uploadBtn: 'Yerel duvar kağıdı seç',
        resetBtn: 'Bing günlük olarak sıfırla',
        advToggle: 'Gelişmiş',
        searchLabel: 'Arama çubuğu görünümü',
        searchHover: 'Üzerine gelince göster',
        searchAlways: 'Her zaman görünür',
        searchNever: 'Her zaman gizli',
        opacityLabel: 'Simge opaklığı',
        engineLabel: 'Arama motoru',
        resetAdv: 'Varsayılanı geri yükle',
        langPanelTitle: 'Dil',
        addImage: 'Duvar kağıdı ekle',
        deleteImage: 'Kaldır',
        imageCount: 'görsel',
        resetConfirm: 'Tüm yerel duvar kağıtları kaldırılsın mı? Geri alınamaz.'
    },
    'pl': {
        extName: 'PlainTab · Minimalistyczna strona startowa',
        searchPlaceholder: 'Szukaj w internecie…',
        engineTitle: 'Kliknij, aby zmienić | Enter, aby szukać',
        langTitle: 'Zmień język',
        settingsTitle: 'Ustawienia tapety',
        panelTitle: 'Tapeta',
        wpBing: 'Bing dnia',
        wpLocal: 'Obraz lokalny',
        uploadBtn: 'Wybierz lokalną tapetę',
        resetBtn: 'Przywróć Bing dnia',
        advToggle: 'Zaawansowane',
        searchLabel: 'Widoczność paska wyszukiwania',
        searchHover: 'Pokaż po najechaniu',
        searchAlways: 'Zawsze widoczny',
        searchNever: 'Zawsze ukryty',
        opacityLabel: 'Przezroczystość ikony',
        engineLabel: 'Silnik wyszukiwania',
        resetAdv: 'Przywróć domyślne',
        langPanelTitle: 'Język',
        addImage: 'Dodaj tapetę',
        deleteImage: 'Usuń',
        imageCount: 'obrazów',
        resetConfirm: 'Usunąć wszystkie lokalne tapety? Nie można cofnąć.'
    },
    'vi': {
        extName: 'PlainTab · Trang bắt đầu tối giản',
        searchPlaceholder: 'Tìm kiếm trên Web…',
        engineTitle: 'Nhấp để đổi công cụ | Enter để tìm',
        langTitle: 'Đổi ngôn ngữ',
        settingsTitle: 'Cài đặt hình nền',
        panelTitle: 'Hình nền',
        wpBing: 'Bing hàng ngày',
        wpLocal: 'Ảnh cục bộ',
        uploadBtn: 'Chọn hình nền cục bộ',
        resetBtn: 'Đặt lại về Bing hàng ngày',
        advToggle: 'Nâng cao',
        searchLabel: 'Hiển thị thanh tìm kiếm',
        searchHover: 'Hiện khi di chuột',
        searchAlways: 'Luôn hiển thị',
        searchNever: 'Luôn ẩn',
        opacityLabel: 'Độ mờ biểu tượng',
        panelOpacityLabel: 'Độ mờ bảng',
        engineLabel: 'Công cụ tìm kiếm',
        resetAdv: 'Khôi phục mặc định',
        langPanelTitle: 'Ngôn ngữ',
        addImage: 'Thêm hình nền',
        deleteImage: 'Xóa',
        imageCount: 'ảnh',
        resetConfirm: 'Xóa tất cả hình nền cục bộ? Không thể hoàn tác.'
    }
};

// 命令面板新增的 i18n key，挂载在 I18N 上便于 t() 查找
// 只完整定义 zh-CN 和 en，其余语言缺 key 时 t() 会回退到 en → raw key
(function () {
    var newKeys = {
        recommend: 'Recommended',
        allShortcuts: 'All Shortcuts',
        searchResults: 'Search Results',
        noResults: 'No matching shortcuts',
        noShortcuts: 'No shortcuts yet. Type /add to create one.',
        addShortcut: 'Add Shortcut',
        editShortcut: 'Edit Shortcut',
        deleteShortcut: 'Delete Shortcut',
        shortcutName: 'Name (e.g. GitHub)',
        shortcutURL: 'URL (e.g. https://github.com)',
        fetchTitle: 'Fetch page title',
        fetchingTitle: 'Fetching title…',
        nameRequired: 'Name is required',
        urlRequired: 'Please enter a valid https:// URL',
        duplicateURL: 'This URL already exists',
        add: 'Add',
        save: 'Save',
        added: 'Added',
        yes: 'Yes, delete',
        no: 'Cancel',
        commands: 'Commands',
        expandShortcutLinks: 'Show shortcut links',
        collapseShortcutLinks: 'Hide shortcut links',
        helpAdd: 'Add a new shortcut',
        helpEdit: 'Edit an existing shortcut',
        helpDelete: 'Delete a shortcut',
        helpRecent: 'Show recently opened shortcuts',
        helpSortAZ: 'Sort alphabetically (A-Z)',
        helpSortFreq: 'Sort by usage frequency',
        helpImport: 'Import from browser bookmarks',
        helpExport: 'Export current panel shortcuts as JSON',
        helpClear: 'Delete shortcuts in the current panel',
        helpRestore: 'Restore default shortcuts',
        helpHide: 'Hide a shortcut',
        helpUnhide: 'Unhide a shortcut',
        helpReset: 'Reset all usage frequencies',
        recentShortcuts: 'Recent',
        noRecentShortcuts: 'No recent shortcuts',
        clearConfirm: 'Delete shortcuts in this panel? This cannot be undone.',
        cpHotkeyLabel: 'Command Palette Shortcut',
        cpRecommendLabel: 'Show recommendations',
        cpSearchPlaceholder: 'Search name or URL...',
        hiddenModeHint: 'Hidden mode — press Esc to close then Ctrl+K',
        normalModeHint: 'Normal mode — press Esc to close then Ctrl+Shift+K',
        hideShortcutTitle: 'Hide Shortcuts',
        hiddenShortcuts: 'Hidden',
        noHiddenShortcuts: 'No hidden shortcuts',
        backToList: 'Back to list',
        toggleView: 'Toggle view'
    };
    var zhCN = {
        recommend: '推荐',
        allShortcuts: '全部快捷链接',
        searchResults: '搜索结果',
        noResults: '未找到匹配的快捷链接',
        noShortcuts: '暂无快捷链接，输入 /add 创建',
        addShortcut: '新建快捷链接',
        editShortcut: '编辑快捷链接',
        deleteShortcut: '删除快捷链接',
        shortcutName: '名称 (如 GitHub)',
        shortcutURL: '链接 (如 https://github.com)',
        fetchTitle: '自动获取名称',
        fetchingTitle: '正在获取标题…',
        nameRequired: '请输入名称',
        urlRequired: '请输入有效的 https:// 链接',
        duplicateURL: '该链接已存在',
        add: '确定',
        save: '保存',
        added: '已添加',
        yes: '确定删除',
        no: '取消',
        commands: '可用命令',
        helpAdd: '新建快捷链接',
        helpEdit: '编辑快捷链接',
        helpDelete: '删除快捷链接',
        helpRecent: '最近使用的快捷链接',
        helpSortAZ: '按字母排序 (A-Z)',
        helpSortFreq: '按使用频率排序',
        helpImport: '从浏览器书签导入',
        helpExport: '导出为 JSON 文件',
        helpClear: '清空所有快捷链接',
        helpHide: '隐藏快捷链接',
        helpUnhide: '取消隐藏快捷链接',
        helpReset: '重置所有使用频率',
        recentShortcuts: '最近使用',
        noRecentShortcuts: '暂无使用记录',
        clearConfirm: '确定删除所有快捷链接？此操作不可撤销。',
        cpHotkeyLabel: '命令面板快捷键',
        cpRecommendLabel: '显示频率推荐',
        cpSearchPlaceholder: '搜索名称或网址...',
        hiddenModeHint: '当前隐藏模式 — 请按 Esc 关闭后再按 Ctrl+K',
        normalModeHint: '当前普通模式 — 请按 Esc 关闭后再按 Ctrl+Shift+K',
        hideShortcutTitle: '隐藏快捷链接',
        hiddenShortcuts: '已隐藏',
        noHiddenShortcuts: '没有隐藏的快捷链接',
        backToList: '返回主列表',
        toggleView: '切换视图模式'
    };
    for (var lang in window.I18N) {
        var base = (lang === 'zh-CN') ? zhCN : newKeys;
        for (var k in base) {
            if (!window.I18N[lang][k]) window.I18N[lang][k] = base[k];
        }
    }
})();

// RSS wallpaper settings i18n. Full zh-CN/en copy; other languages receive English fallback.
(function () {
    var en = {
        rssTest: 'Test',
        rssAdd: 'Add',
        rssNamePlaceholder: 'Source name',
        rssRefreshInterval: 'Auto refresh',
        rssRefreshOff: 'Off',
        rssSummaryPosition: 'Summary position',
        rssSummaryMode: 'Summary display',
        rssExpanded: 'Expanded strip',
        rssIconOnly: 'i button',
        rssShowSummary: 'Show summary',
        rssShowLink: 'Show article link',
        rssStatusError: 'RSS status: ',
        rssStatusCached: 'Cached',
        rssStatusEmpty: 'No RSS images cached yet',
        rssLimit: 'Up to 5 RSS sources',
        rssInvalidUrl: 'Enter an https:// URL',
        rssTesting: 'Testing...',
        rssTestOk: 'Test passed. Image entries: ',
        rssTestFailed: 'Test failed: ',
        rssNoImages: 'Test failed: this RSS feed has no usable image entries',
        rssNoUsableImages: 'Image entries were found, but images could not be downloaded or thumbnailed',
        rssPermissionDenied: 'Permission to access this RSS feed was denied',
        rssParseFailed: 'RSS content could not be parsed',
        rssFetchFailed: 'RSS request failed. Check the link or try again later',
        rssTimeout: 'RSS request timed out. Try again later',
        rssOpenArticle: 'Open article',
        wallpaperResetDefaults: 'Restore Wallpaper Defaults',
        wallpaperResetConfirm: 'This will clear upload, RSS, API, and folder wallpaper cache, restore RSS defaults, and switch back to Bing. Continue?',
        top: 'Top',
        bottom: 'Bottom'
    };
    var zhCN = {
        rssTest: '测试',
        rssAdd: '添加',
        rssNamePlaceholder: '源名称',
        rssRefreshInterval: '自动拉取',
        rssRefreshOff: '关闭',
        rssSummaryPosition: '摘要位置',
        rssSummaryMode: '摘要展示',
        rssExpanded: '展开条带',
        rssIconOnly: 'i 按钮',
        rssShowSummary: '显示摘要',
        rssShowLink: '显示正文链接',
        rssStatusError: 'RSS 状态：',
        rssStatusCached: '已缓存',
        rssStatusEmpty: '尚未缓存 RSS 图片',
        rssLimit: '最多 5 个 RSS 源',
        rssInvalidUrl: '请输入 https:// 链接',
        rssTesting: '正在测试...',
        rssTestOk: '测试通过，可用图片条目：',
        rssTestFailed: '测试失败：',
        rssNoImages: '测试失败：该 RSS 没有可用图片条目',
        rssNoUsableImages: '找到图片条目，但图片无法下载或生成缩略图',
        rssPermissionDenied: '没有获得该 RSS 地址的访问权限',
        rssParseFailed: 'RSS 内容无法解析',
        rssFetchFailed: 'RSS 请求失败，请检查链接或稍后重试',
        rssTimeout: 'RSS 请求超时，请稍后重试',
        rssOpenArticle: '查看正文',
        wallpaperResetDefaults: '恢复默认壁纸设置',
        wallpaperResetConfirm: '这会清理上传、RSS、API 和文件夹壁纸缓存，恢复 RSS 默认源，并切回 Bing。继续吗？',
        top: '上方',
        bottom: '下方'
    };
    Object.keys(window.I18N).forEach(function (lang) {
        var base = lang === 'zh-CN' ? zhCN : en;
        Object.keys(en).forEach(function (key) {
            if (!window.I18N[lang][key]) window.I18N[lang][key] = base[key] || en[key];
        });
    });
})();

window.LanguageList = [
    { code: 'zh-CN', name: '中文 (简体)' },
    { code: 'zh-TW', name: '中文 (繁體)' },
    { code: 'en', name: 'English' },
    { code: 'es', name: 'Español' },
    { code: 'hi', name: 'हिन्दी' },
    { code: 'ar', name: 'العربية' },
    { code: 'pt', name: 'Português' },
    { code: 'ru', name: 'Русский' },
    { code: 'ja', name: '日本語' },
    { code: 'de', name: 'Deutsch' },
    { code: 'ko', name: '한국어' },
    { code: 'fr', name: 'Français' },
    { code: 'it', name: 'Italiano' },
    { code: 'tr', name: 'Türkçe' },
    { code: 'pl', name: 'Polski' },
    { code: 'vi', name: 'Tiếng Việt' }
];
